"""
Django settings for dshk project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fm=ds29a)z9je*p_2*b*ol+v%uer_b7s&errnrgry0#-n*vjr%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['api.dshk.uz','dshk.uz','127.0.0.1','192.168.1.115','gis.dshk.uz']


SESSION_COOKIE_AGE = 60 * 60 * 24 * 1    # 1 kun

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'proj.apps.ProjConfig',
    'django_crontab',
    'leaflet',
]



CRONJOBS = [
    # ('15 3 * * *', 'proj.api.run_api_apz',[True],{},'>>/home/www/dshk/apz_cron.log'),
    # ('20 3 * * *', 'proj.api.run_api_psd',[True],{},'>>/home/www/dshk/psd_cron.log'),
    # ('25 3 * * *', 'proj.api.run_api_psd_ind',[True],{},'>>/home/www/dshk/psd_ind_cron.log'),
    # ('30 3 * * *', 'proj.api.run_api_perm_rec',[True],{},'>>/home/www/dshk/perm_rec_cron.log'),
    # ('35 3 * * *', 'proj.api.run_api_smr',[True],{},'>>/home/www/dshk/smr_cron.log'),
    # ('40 3 * * *', 'proj.api.run_api_pexpl',[True],{},'>>/home/www/dshk/pexpl_cron.log'),
    # ('45 3 * * *', 'proj.api.run_api_pexpl_ind',[True],{},'>>/home/www/dshk/pexpl_ind_cron.log'),
    #
    # ('15 7,13 * * *', 'proj.api.run_api_apz',[False],{},'>>/home/www/dshk/apz_cron.log'),
    # ('20 7,13 * * *', 'proj.api.run_api_psd',[False],{},'>>/home/www/dshk/psd_cron.log'),
    # ('25 7,13 * * *', 'proj.api.run_api_psd_ind',[False],{},'>>/home/www/dshk/psd_ind_cron.log'),
    # ('30 7,13 * * *', 'proj.api.run_api_perm_rec',[False],{},'>>/home/www/dshk/perm_rec_cron.log'),
    # ('35 7,13 * * *', 'proj.api.run_api_smr',[False],{},'>>/home/www/dshk/smr_cron.log'),
    # ('40 7,13 * * *', 'proj.api.run_api_pexpl',[False],{},'>>/home/www/dshk/pexpl_cron.log'),
    # ('45 7,13 * * *', 'proj.api.run_api_pexpl_ind',[False],{},'>>/home/www/dshk/pexpl_ind_cron.log')
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'dshk.middleware.OnlineNowMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

BASICAUTH_USERS={"e_kadastr":'e_kadastr@123','user':'pass'}

ROOT_URLCONF = 'dshk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dshk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'dshk_uz',
        'USER': 'postgres',
        'PASSWORD': 'pgadmin4@123',
        'HOST': 'localhost',
        'PORT': '5432',                      # Set to empty string for default.
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = 'proj/static/'
DOCS_ROOT='proj/docs_for_pod9'

STATIC_URL = '/static/'

LEAFLET_CONFIG={
'DEFAULT_CENTER':(41.41264,63.454122),
'DEFAULT_ZOOM':6,
'MAX_ZOOM':20,
'MIN_ZOOM':1,
# 'SCALE': 'both',

'TILES':[

('OpenStreetMap','http://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/ {y}.png',
    {'attribution':'OpenStreetMap'}),

('GoogleStreet','http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
            { 'maxZoom': 20,
              'subdomains':['mt0','mt1','mt2','mt3'],
               'attribution':'GoogleStreet',
            }),

('GoogleTerrain','http://{s}.google.com/vt/lyrs=p&x={x}&y={y}&z={z}',
            { 'maxZoom': 20,
              'subdomains':['mt0','mt1','mt2','mt3'],
               'attribution':'GoogleStreet',
            }),
('GoogleHybrid','http://{s}.google.com/vt/lyrs=s,h&x={x}&y={y}&z={z}',
            { 'maxZoom': 20,
              'subdomains':['mt0','mt1','mt2','mt3'],
               'attribution':'GoogleStreet',
            }),

('GoogleSet','http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
    {
               'maxZoom': 20,
              'subdomains':['mt0','mt1','mt2','mt3'],
               'attribution':'GoogleSet'}),




],

'ATTRIBUTION_PREFIX':'',
# 'MINIMAP':True,
# 'RESET_VIEW':False,
#'ATTRIBUTION_PREFIX':"<a href='http://www.uzgashkliti.uz'>Uzgashkliti</a>",


}





EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ravotcha1992@gmail.com'
EMAIL_HOST_PASSWORD = 'mannon_1101'
